[package]
name = "Shop Around"
description = "Shop Around allows you to purchase items from stores by activating them directly."
authors = [ "Merlord",]
version = "1.0.4"

[dependencies.mwse]
buildnumber = 4079

[dependencies.mge-xe]
version = ">=0.16.0"
